name 'pathogen'
maintainer 'David Pell'
maintainer_email 'davidcpell@gmail.com'
license 'all_rights'
description 'Installs/Configures pathogen'
long_description 'Installs/Configures pathogen - a vim runtimepath/plugin manager'
version '0.1.0'
